### ISSUE TITLE
Consider removing jsonify which is Public Domain

### ISSUE THREAD

**Issue by masutaka** [liam-hq/liam#111]
## Task description

Consider whether jsonify, which is in the public domain, can be removed and lead to necessary action.

## Background

jsonify is `Public Domain`.
https://github.com/ljharb/jsonify/blob/v0.0.1/package.json#L48

Public domain is not a software license. It is a state in which copyright is abandoned. In some countries or regions, copyright cannot be abandoned, so I would like to stop using jsonify if possible.

The dependencies of jsonify are as follows:

```
$ pnpm -r why jsonify
Legend: production dependency, optional only, dev only

@packages/figma-to-css-variables /Users/masutaka/src/github.com/liam-hq/liam/frontend/packages/figma-to-css-variables

dependencies:
style-dictionary 4.1.3
├─┬ @bundled-es-modules/glob 10.4.2
│ └─┬ patch-package 8.0.0
│   └─┬ json-stable-stringify 1.1.1
│     └── jsonify 0.0.1
└─┬ patch-package 8.0.0
  └─┬ json-stable-stringify 1.1.1
    └── jsonify 0.0.1
```

## TODO (Optional)

- [ ] Consider whether jsonify can be removed -> Yes/No
- [ ] Yes: Create an issue to remove jsonify
- [ ] No: The team must agree to the following:
    - CI fails when a new jsonify version is released. If the license is still Public Domain, execute the following command:

```console
$ cd frontend
$ license_finder approvals add 'jsonify' \
 --version='NEW VERSION' \
 --why 'Public Domain is compatible with Apache-2.0. But it is not a software license. See https://github.com/liam-hq/liam/issues/111' \
 --who '...'
```

## Additional notes (Optional)

* https://github.com/ds300/patch-package/issues/494
