### ISSUE TITLE
Permit `Python-2.0` license instead of `argparse` package

### ISSUE THREAD

**Issue by masutaka** [liam-hq/liam#115]
## Task description

Pemit `Python-2.0` license instead of `argparse` package.

## Background

* The only package that uses the `Python-2.0` license used by Liam is [argparse](https://www.npmjs.com/package/argparse).
* [License Finder](https://github.com/pivotal/LicenseFinder) supports the `Python 2.0` format, but not `Python-2.0`.
* Therefore, we now allow the argparse package instead of the `Python-2.0` license. The version  is pinned to `2.0.1`, so if the version changes, CI will drop and we will notice.

https://github.com/liam-hq/liam/blob/5f70147fd4f6930b91e181979ec446ca6bd76615/config/dependency_decisions.yml#L56-L64

When the following PR are merged and a new version of License Finder is released, it can be made to allow the license as well as others.

* https://github.com/pivotal/LicenseFinder/pull/1053

## TODO (Optional)

- [ ] https://github.com/pivotal/LicenseFinder/pull/1053 is merged
- [ ] New version of License Finder is released, including the above PR commit
- [ ] Permit license for `Python-2.0` instead of `argparse` package

## Additional notes (Optional)

If the PR merge takes a long time, you can use the [specific_install](https://rubygems.org/gems/specific_install) gem, which allows you to gem install a branch of License Finder's fork repository.
