### ISSUE TITLE
Remove the approval of `spawndamnit` package in License Decisions file

### ISSUE THREAD

**Issue by masutaka** [liam-hq/liam#215]
## Task description

Remove the approval of `spawndamnit` package in License Decisions file:

https://github.com/liam-hq/liam/blob/8931cdbfdb65f538bde5f8a46e249a4f53d2c3a3/frontend/config/dependency_decisions.yml#L84-L91

## Background

There was a difference between the [LICENSE](https://github.com/jamiebuilds/spawndamnit/blob/v3.0.1/LICENSE) file in the repository and [the license in package.json](https://github.com/jamiebuilds/spawndamnit/blob/v3.0.1/package.json#L8), and License Finder failed to determine the license, so I created the following PR:

* https://github.com/jamiebuilds/spawndamnit/pull/11

## TODO

- [ ] https://github.com/jamiebuilds/spawndamnit/pull/11 was merged
- [ ] A new version of spawndamnit was released that includes the above PR commit
- [ ] The above version of spawndamnit was introduced in this liam repository

**Comment by MH4GF** [comment]
Not yet merged
https://github.com/jamiebuilds/spawndamnit/pull/11
